spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

file:
  rootPath: D:\upload
  imgPath: /img/


logging:
  level:
    root: info
    com.mcs.mall: debug

